### PR TITLE
Final Milestone: Final Version of Sign up page

### PR DESCRIPTION
**Pull request by AhmedTohamy01**
**MINT Sign up page Final Milestone.**

In this Milestone we have added the following;
- Header section contains button to sign-in if you have account & link to reset your password if your forgot your password.

- Form section contains  sign-up  form has 3 fields : Email Address, Phone and Password.
It contains also link to terms & Privacy policy.

- Footer section contains disclaimer.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @AhmedTohamy01 and @JasemDuncan 
### You have done well :clap: Before, your project can be approved, fix this issue.
- Run your html file on w3 validator and solve the issues, use [this link](https://validator.w3.org/#validate_by_upload)
validator
### Make the changes and resubmit for another code review. Good luck.
- Happy coding!

**Comment by JasemDuncan** [comment]
Good day, Using h2-h6 elements is a non-normative usage recommendation. I could have used DIV elements to avoid this warning but I think the proper way is to use SECTIONS elements.
Besides this is a warning.

https://stackoverflow.com/questions/24155024/w3c-html-validation-error-section-lacks-heading-consider-using-h2-h6-elements

**Comment by AhmedTohamy01** [comment]
@rOluochKe 
Hi man, thank you so much for your review,

Actually it' just a warnings not errors . it asks us to add "heading" with <h> element here but this section doesn't need any <h> element as you can see in the design.

please approve it since we cannot add a <h> here due to the design.
 
Thank you for understanding

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi Team 👋

You've done quite well in this. @AhmedTohamy01 and @JasemDuncan 👍
The project looks great, just a few minor changes and it would look awesome.👇

Kindly make the following changes:

- [ ] Required - Kindly add the icons ass seen on the original page. There should be an icon on the form submit button and also on the Sign In button at the top corner of the page.
**THESE IS YOURS👇**
ice_screenshot_20200408-091349
ice_screenshot_20200408-091359


**THIS IS THE WAY THE ORIGINAL LOOKS**👇
ice_screenshot_20200408-090510
ice_screenshot_20200408-090520

- [ ] Required - In addition ensure that the buttons stated above are clickable just as in the original webpage.

- [ ] Required - Also kindly ensure that the three elements shown below are links as seen in the original.[Screenshot]👇
ice_screenshot_20200408-091420

 - [ ] Required - Kindly change the name of your HTML file to `index.html` and fix the HTML5 validation errors with this [tool](https://validator.w3.org/nu/#file).

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by thsvr** [comment]
### **STATUS: PROJECT APPROVED** :100: :1st_place_medal: :100: 

Hi @AhmedTohamy01 and @JasemDuncan :smile: :smile: 

Congrats on your hard work, guys! Your page looks professional and beautiful. You have been doing a great job and your project was approved :fireworks: :fireworks: :fireworks: :fireworks:



_SUGGESTION FOR THE NEXT PROJECTS:_

:v: You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''mint-page'' instead of ''feature-branch', for example. It will be more descriptive. :smile_cat: :+1: 

:v: This is a wonderful resource for icons [fontawesome](https://fontawesome.com/)
Take a few minutes to take a look at it, you guys will love it :smile_cat: It is simple to use and helps the project looks professional :muscle: 



If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next project** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Pull request merged**
